### ISSUE TITLE
Install fails with dependency error

### ISSUE THREAD

**Issue by xobs** [andrewbrey/wael#1]
When attempting to install from a fresh clone, `npm` fails:

```
[11:47:32 am] E:/Code/wael> npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: wael@1.0.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!   peer react@">=16.8" from @remix-run/react@1.3.4
npm ERR!   node_modules/@remix-run/react
npm ERR!     @remix-run/react@"1.3.4" from the root project
npm ERR!     peer @remix-run/react@"^1.1.1" from remix-utils@2.11.1
npm ERR!     node_modules/remix-utils
npm ERR!       remix-utils@"2.11.1" from the root project
npm ERR!   1 more (react-dom)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from remix-utils@2.11.1
npm ERR! node_modules/remix-utils
npm ERR!   remix-utils@"2.11.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Sean\AppData\Local\npm-cache\_logs\2023-09-10T03_47_37_392Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Sean\AppData\Local\npm-cache\_logs\2023-09-10T03_47_37_392Z-debug-0.log
```

**Comment by andrewbrey** [comment]
Hi @xobs - this project uses `yarn` to manage dependencies, and your issue is caused by `npm` which is unsupported in this project.

For context, this error is due to how `npm` handles peer dependencies. If you take a look at the release notes for `npm` version 7 (https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major) you'll see that they changed the way peer dependencies are handled. Searching around, you'll find lots of help on the topic, including this thread on StackOverflow: https://stackoverflow.com/questions/64936044/fix-the-upstream-dependency-conflict-installing-npm-packages.

**Comment by xobs** [comment]
I was following the instructions at https://github.com/andrewbrey/wael#building-locally which say to use `npm install`. Is the README.md file out of date then?

**Comment by andrewbrey** [comment]
@xobs yes, I apologize the readme was out of date. I've updated it to reference yarn, but do note that this projects' documentation is not (and is not meant to be) comprehensive as its purpose was simply as a way for me to play around and learn Remix. I do not intend to return to this project to fix any issues that might crop up for anyone else trying to play around with it. 

Hopefully with yarn it's smooth sailing for you, but note also that Remix, Prisma, and all the other tools/libraries in this project have changed a lot in the time since I last touched it.

**Comment by xobs** [comment]
I understand that bitrot is a thing. Thank you for updating the README, and for putting this project out there for others to learn from it.
